name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - appnope=0.1.4
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.15
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.10
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.12
  - aws-sdk-cpp=1.11.329
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - certifi=2024.6.2
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - datasets=2.20.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.14.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.5.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - huggingface_hub=0.23.4
  - idna=3.7
  - importlib-metadata=7.1.0
  - ipykernel=6.29.4
  - ipython=8.25.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libarrow=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgoogle-cloud=2.25.0
  - libgrpc=1.62.2
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libparquet=16.1.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libtorch
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libzlib=1.3.1
  - llvm-openmp=18.1.6
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nomkl=1.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - pandas=2.2.2
  - pexpect=4.9.0
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.46
  - psutil=5.9.8
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - readline=8.2
  - regex=2024.5.15
  - requests=2.32.3
  - setuptools=70.0.0
  - six=1.16.0
  - snappy=1.2.0
  - stack_data=0.6.2
  - sympy=1.12
  - tk=8.6.13
  - tokenizers=0.19.1
  - torchvision=0.18.0
  - tqdm=4.66.4
  - transformers=4.41.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstd=1.5.6
